websocket:
  port: 4444
  schema: ws
http:
  port: 8084
  schema: http

engine:
  engine_type: REDIS
  engine_address: localhost
  engine_port: 6379

authorization:
  authorization_type: token
  authorization_token: test

main:
  gracetime: 1000
  logpath: logfile.log